# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BLOG TITLE
email: email@email.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul
encoding: UTF-8

permalink: /:year/:month/:day/:title/
asset_url: /assets

## (Start)Features
# Social services
facebook:
  app_id:
  username:
github:
  username:
rss_enable: false

# Facebook comment plugin
comment_enabled: true


## (End)Features

main_title:
main_url:

menu_list:    # Add menu
  - menu:
    title: About
    permalink: about

footer_list:    # Add footer menu
  - menu:
    title:
    url:

collections:
  tags:
    output: true
    permalink: /tags/:path/
  authors:
    output: true
    permalink: /authors/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

keep_files: [assets, files]
exclude: [README.md, Gemfile, Gemfile.lock]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
